#!/usr/bin/python

import argparse
from modules import es, config

parser = argparse.ArgumentParser(description='ElasticSearch CLI')

parser.add_argument('-c', action='store', help='Use a defined cluster name')

args = parser.parse_args()
print args.accumulate(args.integers)
