#!/usr/bin/env python

import argparse
from modules import es_index, config

VERSION = '0.02'


def main():
    parser_main = argparse.ArgumentParser(description='ElasticSearch CLI v'
            + VERSION)

    parser_main.add_argument('--version', action='version',
            version=VERSION)

    parser_main.add_argument('--cluster', default='default')

    subparsers_main = parser_main.add_subparsers(title='subcommands',
            description='valid subcommands', help='additional help')

    # index

    subparser_index = subparsers_main.add_parser('index')
    subparser_index = subparser_index.add_subparsers(title='subcommands',
            description='valid subcommands', help='additional help')

    # index create

    subparser_index_create = subparser_index.add_parser('create')
    subparser_index_create.add_argument('indexname')
    subparser_index_create.add_argument('--cluster', default='default')
    subparser_index_create.add_argument('--shards', default=configuration.shards)
    subparser_index_create.add_argument('--replicas', default=configuration.replicas)

    #subparser_index_create.add_argument('indexname', destination=index_create(args.cluster, args.cluster, args.shards, args.replicas)

    # index delete

    subparser_index_delete = subparser_index.add_parser('delete')
    subparser_index_delete.add_argument('indexname')
    subparser_index_delete.add_argument('--cluster', default='default')

    # index health

    subparser_index_health = subparser_index.add_parser('health')
    subparser_index_health.add_argument('indexname')
    subparser_index_health.add_argument('--cluster', default='default')

    # cluster

    subparser_cluster = subparsers_main.add_parser('cluster')
    subparser_cluster = subparser_cluster.add_subparsers(title='subcommands',
            description='valid subcommands', help='additional help')

    # cluster health

    subparser_cluster_health = subparser_cluster.add_parser('health')
    subparser_cluster_health.add_argument('--cluster', default='default')

    # cluster state

    subparser_cluster_state = subparser_cluster.add_parser('state')
    subparser_cluster_state.add_argument('--cluster', default='default')

    # cluster shutdown

    subparser_cluster_shutdown = subparser_cluster.add_parser('shutdown')
    subparser_cluster_shutdown.add_argument('--cluster', default='default')

    # nodes

    subparser_nodes = subparsers_main.add_parser('nodes')
    subparser_nodes = subparser_nodes.add_subparsers(title='subcommands',
            description='valid subcommands', help='additional help')

    # nodes stats

    subparser_nodes_stats = subparser_nodes.add_parser('stats')
    subparser_nodes_stats.add_argument('hostname')
    subparser_nodes_stats.add_argument('--cluster', default='default')

    # nodes shutdown

    subparser_nodes_shutdown = subparser_nodes.add_parser('shutdown')
    subparser_nodes_shutdown.add_argument('hostname')
    subparser_nodes_shutdown.add_argument('--delay')
    subparser_nodes_shutdown.add_argument('--cluster', default='default')

    # end

    args = parser_main.parse_args()
    config.configuration(args.cluster)

if __name__ == "__main__":
    main()
