#!/usr/bin/python

import argparse
from modules import es, config

VERSION = '0.01'

parser_main = argparse.ArgumentParser(description='ElasticSearch CLI')
parser_main.add_argument('--version', action='version',
        version=VERSION)

subparsers_main = parser_main.add_subparsers(title='subcommands', description='valid subcommands', help='additional help')

# index

subparser_index = subparsers_main.add_parser('index')
subparser_index = subparser_index.add_subparsers(title='subcommands',
        description='valid subcommands', help='additional help')

# index create

subparser_index_create = subparser_index.add_parser('create')

# index delete

subparser_index_delete = subparser_index.add_parser('delete')

# index health

subparser_index_health = subparser_index.add_parser('health')

# cluster

subparser_cluster = subparsers_main.add_parser('cluster')
subparser_cluster = subparser_cluster.add_subparsers(title='subcommands',
        description='valid subcommands', help='additional help')

#subparser_cluster.add_argument('--cluster')

# cluster health

#subparser_cluster.add_argument('health')

# cluster state

#subparser_cluster.add_parser('state')

# cluster shutdown

#subparser_cluster.add_parser('shutdown')

# nodes

subparser_nodes = subparsers_main.add_parser('nodes')
subparser_nodes = subparser_nodes.add_subparsers(title='subcommands',
        description='valid subcommands', help='additional help')

# nodes stats

subparser_nodes_stats = subparser_nodes.add_parser('stats')
subparser_nodes_stats.add_argument('name')

# nodes shutdown

subparser_nodes_shutdown = subparser_nodes.add_parser('shutdown')
subparser_nodes_shutdown.add_argument('name')
subparser_nodes_shutdown.add_argument('--delay')

# end

args = parser_main.parse_args()
